### ISSUE TITLE
Not running when ignored builders is not specified

### ISSUE THREAD

**Issue by whit** [aleszoulek/bbnotify#7]
<pre>
whit@bk:~/proj/3rd/bbnotify> python bbnotify.py http://buildbot/url/xmlrpc
Traceback (most recent call last):
  File "bbnotify.py", line 8, in <module>
    main()
  File "/home/whit/proj/3rd/bbnotify/bbnotify/__init__.py", line 43, in main
    Notificator(url, ignore_builders)
  File "/home/whit/proj/3rd/bbnotify/bbnotify/notificator.py", line 87, in __init__
    self.start()
  File "/home/whit/proj/3rd/bbnotify/bbnotify/notificator.py", line 114, in start
    self.refresh()
  File "/home/whit/proj/3rd/bbnotify/bbnotify/notificator.py", line 91, in refresh
    if name not in self.ignore_builders:
TypeError: argument of type 'NoneType' is not iterable
</pre>

but:

<pre>
whit@bk:~/proj/3rd/bbnotify> python bbnotify.py -i '' http://buildbot/url/xmlrpc
</pre>

works fine.

**Comment by aleszoulek** [comment]
Should be fixed.

Please, verify.

**Comment by aleszoulek** [comment]
Verified, closing..
