### ISSUE TITLE
new bb xmlrpc fail

### ISSUE THREAD

**Issue by whit** [aleszoulek/bbnotify#8]
<pre>
whit@whit:~/proj/zzz-others/bbnotify> bbnotify -p xmlrpc http://path/to/buildbot:8013/xmlrpc
Traceback (most recent call last):
  File "/usr/local/bin/bbnotify", line 8, in <module>
    load_entry_point('bbnotify==0.3', 'console_scripts', 'bbnotify')()
  File "/usr/local/lib/python2.6/site-packages/bbnotify-0.3-py2.6.egg/bbnotify/__init__.py", line 65, in main
    Notificator(url, ignore_builders, include_builders, protocol=protocol, group=group)
  File "/usr/local/lib/python2.6/site-packages/bbnotify-0.3-py2.6.egg/bbnotify/notificator.py", line 45, in __init__
    self.start()
  File "/usr/local/lib/python2.6/site-packages/bbnotify-0.3-py2.6.egg/bbnotify/notificator.py", line 89, in start
    self.refresh()
  File "/usr/local/lib/python2.6/site-packages/bbnotify-0.3-py2.6.egg/bbnotify/notificator.py", line 77, in refresh
    self._refresh_icon(name, status['result'])
  File "/usr/local/lib/python2.6/site-packages/bbnotify-0.3-py2.6.egg/bbnotify/notificator.py", line 52, in _refresh_icon
    self.icons[name].set_from_file(join(MEDIA_DIR, self.ICONS.get(result)))
  File "/usr/lib64/python2.6/posixpath.py", line 65, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
</pre>

**Comment by aleszoulek** [comment]
Should be fixed.

Pls, verify.

Sorry, I'll create dev branch for not fully tested code. :)

**Comment by whit** [comment]
Now it works, thanks.
